from modules.handlers import start_handlers
from modules.handlers import admin_add_new_person
from modules.handlers import admin_work_with_investor
from modules.handlers import admin_worker
from modules.handlers import noName
from modules.handlers import investor_handler
from modules.handlers import pool_handlers
from modules.handlers import worker
from modules.handlers import admin_bd
